### ISSUE TITLE
Breaks on high resolution displays

### ISSUE THREAD

**Issue by azy2** [GarrettGunnell/AcerolaFX#1]
Loved the youtube video, it taught me a lot about how post processing effects actually work. I'd love to mess around with your shaders but unfortunately they don't work on my monitors (3440 x 1440 and 3840 x 2160). So I guess put me down for supporting a fix for this. From your FAQ I'm guessing you already know the issue but I'm happy to dump any logs if needed.

**Comment by Asinin3** [comment]
"If there is somehow high demand for 4K shaders, I will make it happen." - Yes please!

**Comment by GarrettGunnell** [comment]
Way more people play at a high resolution than I thought lol, don't worry fellas I'll try to get a fix out by the end of the weekend to get the auto exposure to programatically downscale until it's within thread count limits.

**Comment by GarrettGunnell** [comment]
Resolved with 

https://github.com/GarrettGunnell/AcerolaFX/releases/tag/v2.1.0
