### ISSUE TITLE
Is this visual correct?

### ISSUE THREAD

**Issue by I-Am-Caprico** [GarrettGunnell/AcerolaFX#10]
Hello, really appreciate the shaders!

I noticed that notably in Shadowbringerz zone where I currently am in MSQ the shaders make the game super bright and extra faded.

![noShaders](https://user-images.githubusercontent.com/56192860/190619853-6613d508-e806-42fd-8ba4-cc4ee22fcf92.png)
![withShaders](https://user-images.githubusercontent.com/56192860/190619877-c605adcd-4497-4f3f-a83e-eaf074f9b502.png)

Is this correct behavior or did I mess up somehow?

It makes many of the cutscenes unwatchable because of how much light tones are used and the shaders just make them super bright.

Thanks for the help!

**Comment by GarrettGunnell** [comment]
Hey! Yeah I actually realized the auto exposure settings in the highest quality preset don't match the other 2 presets making it a bit brighter, I fixed this and it will be in the next update.

If you want to adjust it yourself make sure the settings look like this:
![ffxiv_dx11_B1srBBrJfN](https://user-images.githubusercontent.com/32238555/190682603-8dacc620-4632-4183-9187-c96e418fcf28.png)

Additionally it may be that your monitor is making the problem worse so you may need to adjust the gamma correction to your own taste.
