### ISSUE TITLE
HighQuality preset doesn´t work for me

### ISSUE THREAD

**Issue by phlippden** [GarrettGunnell/AcerolaFX#11]
Hey, i don´t know if i am doing something wrog but, low and medium presets workes fine, if i try to turn the high on nothing happens.
allready reinstalled gshade.

if its matter 
                      RTX 3080 
resolution      3440 x 1440, 144Hz

**Comment by GarrettGunnell** [comment]
A few people have had this issue and I have no idea what causes it, it has to somehow be an issue with gshade since the preset works for the majority of people. The medium and high quality presets are basically the same anyways, the SSAO on the high quality is just a little better.
