### ISSUE TITLE
XeGTAO not working correctly underwater

### ISSUE THREAD

**Issue by mybaum** [GarrettGunnell/AcerolaFX#13]
When im underwater with XeGTAO enabled, I get a shadowy outline of my character which is offset up and left a little bit

**Comment by GarrettGunnell** [comment]
Yeah there's no way to fix this since reshade doesn't know when you're underwater, sorry.

**Comment by PlatikaViout** [comment]
This is an old issue, but I'll include the solution in case anyone else stumbles across it.

The depth buffer is affected by FFXIV's "Water Refraction" setting. (Makes everything look slightly wavy when you are underwater)
If you are using shaders that use the depth buffer, you will want to disable this setting or set it to low.
(Setting it to low will make the effect slower, which seems to have a very slight effect on the depth buffer. This should be fine for gameplay without giving up on the whole effect. For screenshots, I recommend turning it off completely, as you may still be able to see it if you look closely. For effects like fog, the low setting might still be "too" noticeable for gameplay.)

("System Configuration" > "Graphics Settings" > "Water Refraction")
