### ISSUE TITLE
XeGTAO is out of sync with models in game

### ISSUE THREAD

**Issue by Oreboat** [GarrettGunnell/AcerolaFX#15]
as stated in the title there is a problem where the XeGTAO effect is not synced with the effects in game and so it looks bad and can be disorienting
https://imgur.com/a/BxDJWDg (image for reference)

**Comment by GarrettGunnell** [comment]
The XeGTAO is working just fine. 

For some reason your depth (or GShade) buffer's resolution does not match the size of your screen, I'd ask for help in the GPOSERS/GShade discord since I have no idea what would be causing that issue.

**Comment by PlatikaViout** [comment]
This is an old issue, but I'll include the solution in case anyone else stumbles upon it.

The depth buffer is affected by FFXIV's "dynamic resolution" setting.
If you are using shaders that use the depth buffer, you will want to disable this setting.

("System Configuration" > "Graphics Settings" > uncheck "Enable dynamic resolution")
