### ISSUE TITLE
all xD

### ISSUE THREAD

**Issue by Kingudabat** [GarrettGunnell/AcerolaFX#16]
![imagen](https://user-images.githubusercontent.com/109186865/194394630-24c0c4c6-a86c-4751-9ec4-8d632578d0bb.png)
 
do all the steps, but XeGTAO  put all red xD.

**Comment by GarrettGunnell** [comment]
You are not on the latest version, please download the newest version and replace the shaders.

https://github.com/GarrettGunnell/AcerolaFX/releases/tag/v3.0.1

**Comment by Kingudabat** [comment]
ty ♥
