### ISSUE TITLE
No options selected on any preset after installation

### ISSUE THREAD

**Issue by Spanglish1337** [GarrettGunnell/AcerolaFX#17]
Greetings, I installed the presets and the shaders and there is not any option selected inside of them, look empty on my end
![image](https://user-images.githubusercontent.com/89648547/196505925-0022d899-49da-4421-9684-dbe88a05a1ba.png)

**Comment by GarrettGunnell** [comment]
This means GShade can't find the shaders, so double check to make sure my shader files are properly in one of the folders defined in the shader search path directories in the GShade `Settings` tab.

**Comment by Spanglish1337** [comment]
> This means GShade can't find the shaders, so double check to make sure my shader files are properly in one of the folders defined in the shader search path directories in the GShade `Settings` tab.

Oh, okay I saw the path, it is different than the "Custom Shader" path specified on the guide though... should I Just put your custom shaders there with the rest of the GShade ones?

**Comment by Spanglish1337** [comment]
FIXED: Okay I managed to add the custom shader path to GSHADE, problem is solved. Thank you!
