### ISSUE TITLE
Shadowbringers: Il Mheg fireflies are square

### ISSUE THREAD

**Issue by Nikki1993** [GarrettGunnell/AcerolaFX#18]
Using any AcerollaFX Preset I exhibit an issue where fireflies in Shadowbringers are "square", the issue can be easily seen by visiting Il Mheg and looks like this

![image](https://user-images.githubusercontent.com/1446529/197323463-a40db946-ee59-48d8-b256-91a8d366196e.png)

Gshade: 3.5.2
Acerolla: 3.1.0
Nvidia GTX 1080 ti with 522.25 driver released on 10/12/2022
Preset: LowestQuality *but happens on any other preset

I have however found out that there is at least 1 user does not exhibit same issue while running the same preset so I am at a loss what's causing it for me but not for them.

**Comment by Nikki1993** [comment]
nvm issue resolved. It was fixed by settings Edge Smoothing to FXAA (it was off for me).

**Comment by GarrettGunnell** [comment]
Yeah, they do some weird things when FXAA is disabled. It's very noticeable on hair as well.

Thanks for figuring it out in case someone else has the problem!
