### ISSUE TITLE
The Boobas

### ISSUE THREAD

**Issue by TenderBacon** [GarrettGunnell/AcerolaFX#2]
I don't know why the shader does this or where else it shows up, but it's very noticeable around the character's breasts. Without any filters present the breasts are a lot smoother, but when the filter is turned on (most noticeable on highest quality) you get these very noticeable polygon shapes of the mesh or something.

![NormalBooba](https://user-images.githubusercontent.com/111648691/185752868-6ea3be43-4a5f-47e0-a811-f697ed131261.PNG)

![PolyBooba](https://user-images.githubusercontent.com/111648691/185752874-c83a305b-7743-435f-92dd-12d476318bbd.PNG)

**Comment by azy2** [comment]
That's probably due to ambient occlusion combined with the fact that the boobs are just naturally low poly. You could try turning AO off and see if that helps.

**Comment by GarrettGunnell** [comment]
Like azy2 said, these are ambient occlusion artifacts due to how low poly ff14 boobas are. You can try messing around with the settings on the shader until they disappear or disable the effect.
