### ISSUE TITLE
FlatShade failed to compile since GSHade 4.0 update

### ISSUE THREAD

**Issue by Spanglish1337** [GarrettGunnell/AcerolaFX#25]
![image](https://user-images.githubusercontent.com/89648547/209458084-5ba93c13-04a3-4900-9a06-d1b0d02dec7a.png)

As image mentions, this shader is failing to compile. I want to confirm if this is not related to AcerolaFX because I could not find any shader with this name in the .zip of the last update of AcerolaFX.

**Comment by shyfeather** [comment]
I also had the same error with the shader. Hopefully it gets a fix soon. This is by far the best shader I've used

**Comment by GarrettGunnell** [comment]
That shader is unrelated to AcerolaFX so it shouldn't affect my shaders at all.

Additionally, with the release of the new GShade update, they removed the effect cloning feature so all my presets are broken and it's not really fixable unfortunately. If you'd like to suggest they bring the feature back in their discord, feel free!
