### ISSUE TITLE
Dark areas crushed to pitch black

### ISSUE THREAD

**Issue by Rukishou** [GarrettGunnell/AcerolaFX#26]
![image](https://user-images.githubusercontent.com/4882633/209564992-c7981b9f-a6d3-4929-8678-a16f05a5ead5.png)
![image](https://user-images.githubusercontent.com/4882633/209564996-4aef5bf5-54ff-4cec-bdf2-1cee84915dc7.png)

I'm using the default AcerolaFX_GameplayLowest with just some small tweaks to color temperature and red saturation and while I really like it overall very dark areas become crushed like this and there's a big loss of detail. I'm unsure which shaders and settings to modify without inadvertently messing up other areas with normal lighting conditions. Any ideas?

**Comment by GarrettGunnell** [comment]
What area is this?

This might be one of the few areas of the game where the shaders get completely gimped

**Comment by Rukishou** [comment]
It's Ultima Thule, the final area in Endwalker, and yeah it's pretty much the worst case scenario as even without any shaders it's super dark, but occasionally there's dark areas in different content as well where the detail gets similarly lost

**Comment by GarrettGunnell** [comment]
Yeah for cases like this I'd just disable the shaders while you're playing there with the hotkey, since it would require considerable compensation to bring out the detail which would blow out and ruin every other area in the game.

**Comment by GarrettGunnell** [comment]
Also the new update brings back the original gameplay preset look, so that might fix it a bit

**Comment by Spanglish1337** [comment]
Sad update from Gshade but at least the gameplay shaders could be saved

**Comment by Spanglish1337** [comment]
Welp, another GShade update, hope it did not break anything again
