### ISSUE TITLE
Layer.Fx failed to compile since GSHade 4.1 update

### ISSUE THREAD

**Issue by Spanglish1337** [GarrettGunnell/AcerolaFX#27]
![image](https://user-images.githubusercontent.com/89648547/209791767-52c60447-17ea-48ae-b8f1-ae0e35b1ff9a.png)

Just want to make sure it is not related to any shaders of AcerolaFX, in case another update needs to be done again

**Comment by GarrettGunnell** [comment]
This has nothing to do with my shaders, so no problems there.
