### ISSUE TITLE
GShade Latest Update Breaks Presets

### ISSUE THREAD

**Issue by vitharr137** [GarrettGunnell/AcerolaFX#28]
Hello!

GShade's update yesterday seems to have broken how presets are coded for previous iterations, I am unable to enable any presets from the install of your shaders at the moment, but there doesn't seem to be any compiling errors in the log. Enabling the features one at a time does cause their effects to show up

**Comment by GarrettGunnell** [comment]
Hey Vitharr,

Yeah this seems to be an issue with GShade not my shaders or presets. It seems like it's working for a lot of people (including myself) but not working for others. What's worked for many people is to do a clean reinstall of gshade and redownload my shaders, but this hasn't worked for a few people.

**Comment by vitharr137** [comment]
Thank you for confirming others were able to get it working! I needed to run a full uninstall (used RevoUninstall to find extra items to remove) then removed all GShade folders from the FFXIV and the Public User directories, then revalidated the game, and finally was able to reinstall GShade and the current presets were functioning again after installing AcerolaFX

**Comment by GarrettGunnell** [comment]
Awesome! Glad you got it working, I will refer others to your solution.

**Comment by xGeekpower** [comment]
Can confirm that the above method worked for me to make AcerolaFX work again.
