### ISSUE TITLE
Errors compliling AutoExposure

### ISSUE THREAD

**Issue by supakritk** [GarrettGunnell/AcerolaFX#3]
![image](https://user-images.githubusercontent.com/7279053/185765189-05c617f0-86d3-4d8a-a06a-e2acdbc37fc2.png)
Seem like there is some problem with the shader

**Comment by GarrettGunnell** [comment]
Yep, as explained in the FAQ the shaders don't support resolutions larger than 2560×1080.

I'll be adding support by the end of the weekend if everything goes well.

**Comment by GarrettGunnell** [comment]
Resolved with

https://github.com/GarrettGunnell/AcerolaFX/releases/tag/v2.1.0
