### ISSUE TITLE
Reimplement shader cloning?

### ISSUE THREAD

**Issue by eddiecho** [GarrettGunnell/AcerolaFX#30]
There was some drama regarding GShade and the outcome of it is looking like most people are migrating to vanilla ReShade. Because of that, I assume there wouldn't be much of an issue with adding back the effects that required the shader cloning?

**Comment by GarrettGunnell** [comment]
All the shader cloning is done in the reshade shader now rather than as part of the gshade gui, so everything will work just fine in base reshade.
