### ISSUE TITLE
ReShade gotchas

### ISSUE THREAD

**Issue by nopjmp** [GarrettGunnell/AcerolaFX#31]
Any gotchas with using ReShade instead? I think an outlined list of gotchas and maybe some help from the community to document the solution may go a long ways to prevent problems.

It appears the latest version is compatible and the shaders compiled but I'm not sure if something is extremely off or not.

I'm willing to contribute documentation for it.

**Comment by GarrettGunnell** [comment]
GShade and ReShade are basically equivalent now so my shaders will work just fine with base ReShade assuming you have the depth info addon that comes prepackaged with it.
