### ISSUE TITLE
Black Screen while using highest gameplay preset

### ISSUE THREAD

**Issue by LuisMSoares** [GarrettGunnell/AcerolaFX#32]
While I'm using the highest gameplay preset I'm having a lot of black screens, just notice that I have a fresh install of reshade and the only addon that I have is the Generic Depth.
[screen1](https://cdn.discordapp.com/attachments/949418299517710366/1072645925677318234/image.png) [screen2](https://cdn.discordapp.com/attachments/949418299517710366/1072646134545272912/image.png)

**Comment by GarrettGunnell** [comment]
This means you probably didn't install the `ReShade with full add on support` at http://static.reshade.me/#download

without that then the depth buffer will flicker and repeatedly be turned off/on by reshade as it detects ff14 network activity, and my shaders make extensive use of the depth buffer resulting in the black screens as the shaders are using a blank depth buffer.
