### ISSUE TITLE
Super bright

### ISSUE THREAD

**Issue by AnzeG8** [GarrettGunnell/AcerolaFX#33]
All the presets seem to be super bright for me. Not getting any errors so I don't think I did anything wrong and the settings are default.
![ffxiv_dx11 2023-02-08 20-32-05 overlay](https://user-images.githubusercontent.com/92861611/217593870-f2f3fd7a-2f98-4b50-af3c-9eea996a0162.png)
Is there something I can change to fix this?

**Comment by GarrettGunnell** [comment]
That's just what my preset looks like. Perceived brightness is monitor dependent, so maybe change your monitor settings or refer to my guide to make changes to the shaders themselves to more suit your liking.
https://github.com/GarrettGunnell/AcerolaFX/wiki/User-Guide
