### ISSUE TITLE
about this sorting shader

### ISSUE THREAD

**Issue by daef** [GarrettGunnell/AcerolaFX#35]
shouldn't you be able to add the location of the pixels to the calculated value that you later sort by, then sort the whole columns with those tuples at once, and then in the next pass you collect the slices like you do now with this spawn for every pixel but every surviving thread can now do a linear scan over the presorted column, filtering the ones it is not interrested in out (it knows what it's interrested in as of now: start and length, in the scan just ignore values which position lies outside, the remainder stays sorted)

sorry, i dont have the game and no idea to run this stuff on linux, otherwise i would probably try to cobble together a pull request.

**Comment by GarrettGunnell** [comment]
i dunno implement it and find out
