### ISSUE TITLE
Aborting due to not yet implemented feature: Uniform initializer.

### ISSUE THREAD

**Issue by Famf** [GarrettGunnell/AcerolaFX#36]
I'm trying to use this with the XIVLauncher flatpak on Linux. When installing ReShade_Setup_5.7.0_Addon.exe I select ffxiv_dx11.exe and proceed with all the defaults. It did not make a reshade-presets folder so I created one myself. After installing AcerolaFX files to the appropriate folders I launch the game and get errors such as: 
game\reshade-shaders\Shaders\ChromaticAberration.fx":
error: F__PostProcessVS: <anonymous>:24:2: E5017: Aborting due to not yet implemented feature: Uniform initializer.

and 

game\reshade-shaders\Shaders\AcerolaFX_Alpha.fx":
<anonymous>:9:2: E5017: Aborting due to not yet implemented feature: Uniform initializer.
<anonymous>:11:2: E5017: Aborting due to not yet implemented feature: Uniform initializer.
<anonymous>:12:2: E5000: syn

tax error, unexpected NEW_IDENTIFIER

I've attached my reshade.log for all the error messages. 
[ReShade.log](https://github.com/GarrettGunnell/AcerolaFX/files/11108011/ReShade.log)

I've also attached images of my directories to make sure I didn't mess any of that up.
![Screenshot_20230330_002519](https://user-images.githubusercontent.com/7673224/228738337-c5c9e236-b73f-4c4a-bd15-af4812a6e82c.png)

![Screenshot_20230330_002639](https://user-images.githubusercontent.com/7673224/228738588-d0a74553-b6ca-4b13-87dd-fec0d1041605.png)

![Screenshot_20230330_002755](https://user-images.githubusercontent.com/7673224/228738601-9449915d-9ed4-45e1-a6db-78188142fdfe.png)

**Comment by GarrettGunnell** [comment]
I'm guessing this is because you're on Linux. Unfortunately since I am on Windows, I can't really help you fix the issue.
