### ISSUE TITLE
Activating XeGTAO makes my screen go black

### ISSUE THREAD

**Issue by Ty0sMatic** [GarrettGunnell/AcerolaFX#37]
Heyhey, i just installed the newest update of reshade and added the newest version of your FFXIV shaders as well. Immediately the screen went black and all that was left to see was the HUD. I figured out that turning off the AO returns my image but it's suuuuper bright now for some reason. What could be the cause of this? I have not altered the presets in any way.

**Comment by GarrettGunnell** [comment]
This means ReShade is either broken now or you installed the wrong version of ReShade, please make sure you installed the ReShade with full add-on support.
