### ISSUE TITLE
AFX_AutoExposure failed to compile

### ISSUE THREAD

**Issue by VaracolacisCrew** [GarrettGunnell/AcerolaFX#4]
Seems that the auto exposure has some compiling error on high or non standard resolutions 
if i go to my 4k display (3840 x 2160) it cant compile with error:
110, 1-24 error x3655 : the product of the arguments  of numthreads(2040, 1, 1) must be less or equal to 1024

and even tho I know programming i have never mess with shaders nor gshade other than presets. So I dont even know where to look for the problem other than trying to find out the operation (havent found it yet)

**Comment by GarrettGunnell** [comment]
Is this an issue with the latest version 2.1.0? Because it should have been solved.

**Comment by VaracolacisCrew** [comment]
> 

oh no man, i just saw an update and now it is working like a charm. Thank you!
I'll look at the code, would be great to understand shaders :D

**Comment by GarrettGunnell** [comment]
No problem, thanks for using the shaders!
