### ISSUE TITLE
XeGTAO and Bloom shaders don't compile in opengl games

### ISSUE THREAD

**Issue by Bruno-Jambeiro** [GarrettGunnell/AcerolaFX#40]
Every time I tried using these shaders with an OpenGL game, the following error occurred:

![errors](https://github.com/GarrettGunnell/AcerolaFX/assets/62389696/74731081-37bf-4c69-9140-bd0358f34877)

In the XeGATAO shaders, the errors come from the CS_Denoise function receiving a uint2 as a parameter instead of a uint3. Changing that resolved the shader compilation issue. 

In the Bloom shader, simply changing everything to int instead of bool also seems to solve the problem.

**Comment by GarrettGunnell** [comment]
I only ensure my shaders compile and work on ff14, I'm glad you figured out the issue though.
