### ISSUE TITLE
AutoExposure Shader fails to compile on very high resolutions (6K and above)

### ISSUE THREAD

**Issue by JSEverything** [GarrettGunnell/AcerolaFX#42]
Log:
`18:05:45:161 [07724] | ERROR | Failed to compile "D:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online\game\reshade-shaders\Shaders\AcerolaFX_AutoExposure.fx":
D:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online\game\Shader@0x000001875B6A0040(740,1-24): error X3655: the product of the arguments of numthreads(1148,1,1) must be less than or equal to 1024`

This happens when trying to take a screenshot in resolutions higher than 4K, the exact error is for 5760x3240.
I'm using a plugin (Simple Tweaks) which has an option of temporairly increasing the game's resolution beyond what can be displayed on your monitor when taking screenshots using the in-game hotkey, but I think this would behave in the same way if you run the game at that resolution without plugins.

If it matters, I'm using ReShade 5.9.2.1760, the GPU is a GTX 1080, driver 537.13.

**Comment by GarrettGunnell** [comment]
taking higher resolution screenshots is kind of meaningless with a game like ff14, I would recommend just being normal about it and taking 4k screenshots or even 1080p because that's what ff14 was made for.

I also cant fix this because there are genuine hardware limits at play, sorry.
