### ISSUE TITLE
AcerolaFX_BokehBlur.fx auto foucs or mouse focus?

### ISSUE THREAD

**Issue by nx5314** [GarrettGunnell/AcerolaFX#43]
Any plans to implement auto focus or mouse focus functions for the BokehBlur shader?  Focus options are pretty essential when I want to get some shots of a cutscene or anything else in motion.  Either way, thanks for the awesome work with all these

**Comment by GarrettGunnell** [comment]
no plans for auto focus because that's something that is really really hard to do properly and I don't have that kind of time to fine tune especially for a third person game like ff14.

Mouse focus though, maybe one day if I'm feeling bored!
