### ISSUE TITLE
Dawntrail Updates

### ISSUE THREAD

**Issue by m-gora** [GarrettGunnell/AcerolaFX#45]
Despite the engine switch and lighting updates, the game looks still not as good as it could be.

Are you planning to update this shader pack for dawntrail? I see that XeGTAO breaks the rendering and at the moment I use the builtin GTAO.

**Comment by GarrettGunnell** [comment]
yeah, I'm gonna need a bit to update things unfortunately lol I'm very busy. I recommend disabling xegtao for now and tuning the color correction to your liking, the preset should still work pretty well though.

**Comment by rhael-gaming** [comment]
Just wanted to pipe in on this - I was able to resolve the GTAO rendering issue by a simple change in the Global Preprocessor Definitions - change RESHADE_DEPTH_INPUT_IS_REVERSED from 0 to 1. Someone posted about this on exTwitter regarding Reshade back in April with the benchmark tool, I just stumbled on it today after reading this post.

**Comment by GarrettGunnell** [comment]
Alright I needed to fix this in order to finish my new video actually and turns out it's an instant fix and I don't need to release an update, you just need to do as rhael-gaming stated and change the preprocessor definition.

Here's a demo from ipsusu: https://x.com/ipsusu/status/1806621994919526808

have fun with Dawntrail!

**Comment by GarrettGunnell** [comment]
ok actually I just checked the xegtao and it's still broken I believe, will update when I can.

**Comment by GarrettGunnell** [comment]
Alright this has been fixed in the new release, enjoy!

https://github.com/GarrettGunnell/AcerolaFX/releases/tag/v10.1.0

**Comment by RaphaelDDL** [comment]
> Alright this has been fixed in the new release, enjoy!
> 
> https://github.com/GarrettGunnell/AcerolaFX/releases/tag/v10.1.0

Thanks for the upgrade. I upgraded and the screen is now flashing/blinking like an old tv on darker places during day when enabling xegtao, even reshade menu blinks (since is dark gray). 

Is there anything else to config other than the RESHADE_DEPTH_INPUT_IS_REVERSED ?

**Comment by GarrettGunnell** [comment]
If you mean the screen changes brightness when you open menus and stuff then this is because the auto exposure operates on whatever is on the screen and so if the ui covers more of the screen then the auto exposure will adjust accordingly. This is not something that can be fixed.
