### ISSUE TITLE
Presets turning sparkles in Coerthas Western Highlands into squares (10.1.0)

### ISSUE THREAD

**Issue by ghost** [GarrettGunnell/AcerolaFX#46]
Shaders Off
![image](https://github.com/GarrettGunnell/AcerolaFX/assets/28911621/328098ab-d4be-4941-a605-ae26f32c440b)
Shaders On
![image](https://github.com/GarrettGunnell/AcerolaFX/assets/28911621/ad66e45c-af1c-47ec-9593-5cbc29bfb9cf)

Most of the Acerola shaders seem to turn these little shiny bits into squares. I don't recall it happening on older versions of Acerola though. This is after tweaking the depth thing for Dawntrail. Is there any fix to this? Or is there some kind of setting I missed?

**Comment by GarrettGunnell** [comment]
It's definitely not an issue with my shaders but an issue with ff14 itself as usual lol, either these are written to the depth buffer and xegtao occludes them to make them darker or these are written to the alpha buffer and the shaders aren't being drawn on them. There's nothing that can be done outside of invasive reshade addons to change when the shaders are dispatched in the rendering pipeline.
