### ISSUE TITLE
Discoloration issues with the blend shader

### ISSUE THREAD

**Issue by howlingc** [GarrettGunnell/AcerolaFX#48]
In DT the blend shader used in your gameplay presets can cause very noticiable patches of discoloration in some lighting situations.

![Screenshot 2024-07-04 102853](https://github.com/GarrettGunnell/AcerolaFX/assets/18733225/e63f1898-e305-4e9b-a61f-6677bdd26acb)

**Comment by howlingc** [comment]
After some expiremantion ended up changing the blend mode from Acerola Light to Hard Light (Soft Light also does the trick) for the Blend 2 shader. This fixes the previous issue with faces when there are bright light source in front of a face.

**Comment by GarrettGunnell** [comment]
This is called color banding.
