### ISSUE TITLE
AcerolaFX_XeGTAO.fx doesn't load

### ISSUE THREAD

**Issue by danyad22** [GarrettGunnell/AcerolaFX#49]
22:59:08:652 [16812] | ERROR | Failed to compile GLSL shader:
0(2) : warning C7508: extension EXT_control_flow_attributes not supported
0(1653) : error C7011: implicit cast from "uvec3" to "uvec2"

22:59:08:653 [16812] | ERROR | Failed to create compute pipeline for pass 2 in technique 'AFX_XeGTAO'

**Comment by GarrettGunnell** [comment]
My shaders are written for ff14 which is a dx backend and thus are intended to compile to hlsl, if you try these shaders on opengl or vulkan backends they may not work as intended and unfortunately there's nothing that can be done aside from fixing the errors in the code yourself.
