### ISSUE TITLE
Auto Exposure is giving me a wall of yellow errors

### ISSUE THREAD

**Issue by Elliad-Live** [GarrettGunnell/AcerolaFX#5]
![image](https://user-images.githubusercontent.com/10016064/185784919-e44eeced-e603-4057-88f2-317c88f528f9.png)
Is this fine to ignore?

**Comment by JonrGull** [comment]
It is fine to ignore. [As you can see here in his Wiki.](https://github.com/GarrettGunnell/AcerolaFX/wiki#:~:text=performance%20is%20desired.-,Why%20is%20there%20a%20yellow%20warning%20message%20on%20the%20Auto%20Exposure,The%20vertex/frag%20shaders%20are%20not%20actually%20using%20the%20groupshared%20memory.,-How%20can%20I)
