### ISSUE TITLE
Is it possible to disable the bloom effects?

### ISSUE THREAD

**Issue by DrWhoCares** [GarrettGunnell/AcerolaFX#51]
The bloom effect in the FFXIV shaders are extremely bright. They blow out scenes all the time. Praetorium is a good example of this happening, but it also happens everywhere else and on people's equipment.
I've tried looking through the settings for a way of disabling or reducing the amount of blown out bloom there is, but I haven't been able to find anything.

Is this a bug? Or is there a way I can disable it/reduce it? The shaders are very, very nice other than the bloom.

**Comment by GarrettGunnell** [comment]
My gameplay presets do not include bloom, nothing can be done about the base game's bloom without more invasive mods.

**Comment by DrWhoCares** [comment]
In case anyone else wants to try to fix this, I fixed it (at the cost of some graphical fidelity) by lowering the contrast on the color correction shader (this is for graphics highest preset). Original was `1.250, 1.250, 1.350`
![image](https://github.com/user-attachments/assets/158df43b-a765-49bc-845d-9ce05f03ee26)
