### ISSUE TITLE
AcerolaFX 10.1.0 GameplayHighest p12 squares around ambient feathers

### ISSUE THREAD

**Issue by 94Mooni** [GarrettGunnell/AcerolaFX#52]
AcerolaFX 10.1.0 GameplayHighest
p12 squares around ambient feathers

2 second video of the issue:
https://youtu.be/_V7E1xBLE38

screenshot of the issue:
https://i.imgur.com/1brzKju.jpg

**Comment by GarrettGunnell** [comment]
Yeah this is an issue with ff14 itself now including particles in the ui mask, there's nothing that can be done to fix it with my shaders or base reshade. You can try addons like ReShade REST or GShade.
