### ISSUE TITLE
Particle effects

### ISSUE THREAD

**Issue by AlexPNull** [GarrettGunnell/AcerolaFX#54]
There is an issue in some instances where particle effects have visible planes around them and inside those planes the effects from reshade aren't working, a good example of it is in M2 raid

**Comment by GarrettGunnell** [comment]
Yeah this is cause for some reason ff14 masks the particles, the only way to fix it is to disable ui masking in AcerolaFX_End but that'll apply shaders to the whole ui if that bothers you.
