### ISSUE TITLE
A bunch of compile errors.

### ISSUE THREAD

**Issue by claalcmam** [GarrettGunnell/AcerolaFX#6]
Greetings.  Maybe the error is real, or maybe i am barely smart.
i have these:
![image](https://user-images.githubusercontent.com/111689741/185791619-88b4aabf-320c-49dc-8753-419ab20e9b0a.png)

and 

![image](https://user-images.githubusercontent.com/111689741/185791639-05d18cc5-99bb-4772-9522-5b272aa7db5d.png)

It may occur just because i trying to use it somewhere else than Final Fantasy?

**Comment by GarrettGunnell** [comment]
Yeah, the shaders are intended for Final Fantasy XIV only.

**Comment by claalcmam** [comment]
> Yeah, the shaders are intended for Final Fantasy XIV only.

Well... this explains everything.

Many thanks and... it is good job after all.
