### ISSUE TITLE
autoexposore warnings

### ISSUE THREAD

**Issue by Temepest74** [GarrettGunnell/AcerolaFX#7]
I think this is a warning, because it is yellow.
If I hover over Auto Exposure [AceloraFX_AutoExposure.fx] (beside the fact that it is yellow itself) i get this 
![image](https://user-images.githubusercontent.com/28103890/186723543-3c947384-a9fa-4856-8fde-5199a448d384.png)

**Comment by GarrettGunnell** [comment]
Please read the FAQ before opening issues.
