### ISSUE TITLE
Wondering about HDR

### ISSUE THREAD

**Issue by ritmototal** [GarrettGunnell/AcerolaFX#8]
Amazing GShade Preset. Wondering about HDR since you mention it on the description.

I have an HDR10 Gaming Display (1000 nits local dimming..) is there a setting somewhere or a specific preset that utilizes the HDR mode on windows? or are we only simulating HDR into normal displays.

Thanks.

**Comment by GarrettGunnell** [comment]
Since the output of GShade (and ff14) is SDR, we are only simulating HDR like most games do. Unfortunately there's no way to output true to form HDR and if there was then we wouldn't need to do all the tone mapping and auto exposure shenanigans.

**Comment by ritmototal** [comment]
Thank you, what about when using Windows AutoHDR? This seems to be a default on Windows 11 and was introduced sometime during the later updates of Windows 10.

**Comment by GarrettGunnell** [comment]
I'm not sure, it's something you'll have to play around with and experiment with yourself. I don't have an HDR monitor nor do I know what it looks like to use one, so I unfortunately don't have much advice regarding it I'm sorry!

**Comment by ritmototal** [comment]
No problem. The GShade presets are not compatible with windows Autohdr you usually get things too bright etc. Maybe its utilizastion is limited in GShade untill the majority of people have HDR Displays.

Thank you!
